# Generated by Django 3.2 on 2021-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_eventuploader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majourcriteria',
            name='main_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
