# Generated by Django 3.2 on 2021-10-28 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='user',
            field=models.ManyToManyField(related_name='club_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
