# Generated by Django 3.2 on 2021-10-28 02:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('criterion', models.CharField(blank=True, max_length=20, null=True)),
                ('cr_index', models.CharField(blank=True, max_length=20, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
                ('date5', models.DateField(blank=True, null=True)),
                ('date6', models.DateField(blank=True, null=True)),
                ('url1', models.URLField(blank=True, null=True)),
                ('url2', models.URLField(blank=True, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='cr_file1/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='cr_file1/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='cr_file1/')),
                ('file4', models.FileField(blank=True, null=True, upload_to='cr_file1/')),
                ('file5', models.FileField(blank=True, null=True, upload_to='cr_file1/')),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True, null=True)),
                ('text6', models.TextField(blank=True, null=True)),
                ('text7', models.TextField(blank=True, null=True)),
                ('text8', models.TextField(blank=True, null=True)),
                ('text9', models.TextField(blank=True, null=True)),
                ('text10', models.TextField(blank=True, null=True)),
                ('text11', models.TextField(blank=True, null=True)),
                ('text12', models.TextField(blank=True, null=True)),
                ('text13', models.TextField(blank=True, null=True)),
                ('text14', models.TextField(blank=True, null=True)),
                ('text15', models.TextField(blank=True, null=True)),
                ('text16', models.TextField(blank=True, null=True)),
                ('text17', models.TextField(blank=True, null=True)),
                ('text18', models.TextField(blank=True, null=True)),
                ('text19', models.TextField(blank=True, null=True)),
                ('text20', models.TextField(blank=True, null=True)),
                ('text21', models.TextField(blank=True, null=True)),
                ('text22', models.TextField(blank=True, null=True)),
                ('text23', models.TextField(blank=True, null=True)),
                ('text24', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('REVERTED', 'Reverted'), ('OTHER', 'Other'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('jdoc', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
