# Generated by Django 3.2 on 2021-10-28 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterions', '0001_initial'),
        ('adminapp', '0002_eventuploader_department'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionmaster',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='programs.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='criterionmaster',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='programs.clubs', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='criterionmaster',
            name='criteria_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='adminapp.criteriamanager', verbose_name='Criteria Manager'),
        ),
        migrations.AddField(
            model_name='criterionmaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='programs.departments'),
        ),
        migrations.AddField(
            model_name='criterionmaster',
            name='final_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='adminapp.finalcriteria', verbose_name='Final Criteria'),
        ),
        migrations.AddField(
            model_name='criterionmaster',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='programs.subject', verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='criterionmaster',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crm_data', to='programs.program'),
        ),
    ]
